# Generated by Django 3.2.8 on 2021-10-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20)),
                ('itemStatus', models.IntegerField(choices=[(0, 'Pending'), (1, 'Added To Cart'), (2, 'Not Available'), (3, 'Buy Later'), (4, 'Too Expensive'), (5, 'Bought')], default=0)),
                ('marketAmount', models.FloatField(blank=True, default=0, null=True)),
                ('marketAmountDate', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
