# Generated by Django 3.2.8 on 2021-10-08 12:20

import ShoppingListApp.enums.shoppingListItemStatus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Shopping List', 'verbose_name_plural': 'Shopping Lists'},
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='itemStatus',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'InCart'), (2, 'NotAvailable'), (3, 'BuyLater'), (4, 'TooExpensive'), (5, 'Bought')], default=ShoppingListApp.enums.shoppingListItemStatus.ShoppingListItemStatus['Pending']),
        ),
    ]
